// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkv598-vbYDDegZwJ22AOEqUWLD5IVrcw',
    appId: '1:379043271419:web:092b29bc1ab349a370d65e',
    messagingSenderId: '379043271419',
    projectId: 'curiocampus-c8f79',
    authDomain: 'curiocampus-c8f79.firebaseapp.com',
    storageBucket: 'curiocampus-c8f79.firebasestorage.app',
    measurementId: 'G-BP965W43B0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5qCQ9qFjvMxLQjlhpq4dmZudIyY390Lo',
    appId: '1:379043271419:android:f8d025d3193375ca70d65e',
    messagingSenderId: '379043271419',
    projectId: 'curiocampus-c8f79',
    storageBucket: 'curiocampus-c8f79.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3fQkEPZIfLfWqfE9ncVgsYhkrp8oPD0U',
    appId: '1:379043271419:ios:91c1c0af5ee0f74570d65e',
    messagingSenderId: '379043271419',
    projectId: 'curiocampus-c8f79',
    storageBucket: 'curiocampus-c8f79.firebasestorage.app',
    iosBundleId: 'com.example.curioCampus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3fQkEPZIfLfWqfE9ncVgsYhkrp8oPD0U',
    appId: '1:379043271419:ios:91c1c0af5ee0f74570d65e',
    messagingSenderId: '379043271419',
    projectId: 'curiocampus-c8f79',
    storageBucket: 'curiocampus-c8f79.firebasestorage.app',
    iosBundleId: 'com.example.curioCampus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkv598-vbYDDegZwJ22AOEqUWLD5IVrcw',
    appId: '1:379043271419:web:b495cf1e9254f67270d65e',
    messagingSenderId: '379043271419',
    projectId: 'curiocampus-c8f79',
    authDomain: 'curiocampus-c8f79.firebaseapp.com',
    storageBucket: 'curiocampus-c8f79.firebasestorage.app',
    measurementId: 'G-ZX7BZ97SPT',
  );

}